spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tradestore
    username: trade
    password: trade
  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb://localhost:27017/tradestore

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080
