name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build and run tests
        run: ./gradlew clean test jacocoTestReport

      - name: Upload JaCoCo HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-report
          path: build/reports/jacoco/test/html

      - name: Upload JaCoCo XML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-xml-report
          path: build/reports/jacoco/test/jacocoTestReport.xml

      - name: Run OWASP Dependency-Check (no update, not recommended)
        run: ./gradlew dependencyCheckAnalyze --no-daemon -PdependencyCheck.noupdate=true

